<?xml version="1.0"?>

<robot xmlns:xacro="http://ros.org/wiki/xacro">
  <xacro:include filename="$(find crane_plus_description)/urdf/crane_plus_hardware.xacro"/>

  <material name="grey">
    <color rgba="0.75 0.75 0.75 1.0"/>
  </material>
  <material name="black">
    <color rgba="0.2 0.2 0.2 1.0"/>
  </material>

  <xacro:macro name="crane_plus" params="parent servo_color bracket_color
               gripper_color *origin joints_vlimit pan_llimit pan_ulimit">
    <link name="crane_plus_mounting_link"/>
    <joint name="crane_plus_mounting_joint" type="fixed">
      <xacro:insert_block name="origin"/>
      <parent link="${parent}"/>
      <child link="crane_plus_mounting_link"/>
    </joint>

    <!-- TODO: When rviz supports multiple materials per link, combine the
         meshes to simplify the link structure. -->

    <!-- Mounting plate -->
    <mounting_plate
        parent="crane_plus_mounting_link"
        name="crane_plus_internal_mounting_plate"
        color="black">
      <origin xyz="0 0 0" rpy="0 0 0"/>
    </mounting_plate>

    <!-- Base bracket -->
    <bioloid_f53_fixed
        parent="crane_plus_internal_mounting_plate_link"
        name="crane_plus_internal_base_bracket"
        color="grey">
      <origin xyz="0 0 ${MOUNT_HEIGHT}" rpy="0 0 0"/>
    </bioloid_f53_fixed>

    <!-- Shoulder servo -->
    <dynamixel_ax12_fixed
        parent="crane_plus_internal_base_bracket_link"
        name="crane_plus_internal_shoulder_servo"
        color="black">
        <origin xyz="-${AX12_SIDE_SCREW_OFFSET} 0 ${AX12_BODY_MAIN_HEIGHT/2 + F53_HEIGHT}" rpy="0 0 0"/>
    </dynamixel_ax12_fixed>

    <!-- Shoulder bracket -->
    <bioloid_f2_revolute_base_axis
        parent="crane_plus_internal_shoulder_servo_link"
        name="crane_plus_shoulder_revolute"
        color="grey"
        vlimit="${joints_vlimit}"
        llimit="${pan_llimit}"
        ulimit="${pan_ulimit}">
        <origin xyz="-${AX12_AXLE_OFFSET} 0 ${AX12_HORN_HEIGHT}" rpy="0 0 0"/>
    </bioloid_f2_revolute_base_axis>

    <!--Upper arm servo -->
    <dynamixel_ax12_revolute
        parent="crane_plus_shoulder_revolute_link"
        name="crane_plus_shoulder_flex"
        color="black"
        vlimit="${joints_vlimit}"
        llimit="-1.7"
        ulimit="1.7">
        <origin xyz="0 0 ${F2_AXLE_HEIGHT}" rpy="-${M_PI/2} -${M_PI/2} 0"/>
    </dynamixel_ax12_revolute>

    <!-- Upper arm upper joiner -->
    <bioloid_f3_fixed
        parent="crane_plus_shoulder_flex_link"
        name="crane_plus_internal_upper_arm_upper_joiner"
        color="grey">
        <origin xyz="${AX12_ORIGIN_TO_AXLE+AX12_ORIGIN_TO_END_SCREW+F3_SCREW_HEIGHT} 0 0" rpy="-${M_PI/2} 0 ${M_PI/2}"/>
    </bioloid_f3_fixed>

    <!-- Upper arm lower joiner -->
    <bioloid_f3_fixed
        parent="crane_plus_internal_upper_arm_upper_joiner_link"
        name="crane_plus_internal_upper_arm_lower_joiner"
        color="grey">
        <origin xyz="0 0 0" rpy="${M_PI} 0 0"/>
    </bioloid_f3_fixed>

    <!-- Lower arm servo -->
    <dynamixel_ax12_fixed
        parent="crane_plus_internal_upper_arm_lower_joiner_link"
        name="crane_plus_internal_lower_arm_servo"
        color="black">
      <origin xyz="0 0 ${F3_SCREW_HEIGHT+AX12_ORIGIN_TO_END_SCREW}" rpy="0 ${M_PI/2} ${M_PI/2}"/>
    </dynamixel_ax12_fixed>

    <!-- Lower arm bracket -->
    <bioloid_f4_revolute
        parent="crane_plus_internal_lower_arm_servo_link"
        name="crane_plus_elbow"
        color="grey"
        vlimit="${joints_vlimit}"
        llimit="-2.3"
        ulimit="2.3">
        <origin xyz="-${AX12_ORIGIN_TO_AXLE} 0 0" rpy="${M_PI/2} 0 ${M_PI/2}"/>
    </bioloid_f4_revolute>

    <!-- Lower arm joiner -->
    <bioloid_f3_fixed
        parent="crane_plus_elbow_link"
        name="crane_plus_internal_lower_arm_joiner"
        color="grey">
        <origin xyz="0 0 -${F4_AXLE_HEIGHT}" rpy="0 ${M_PI} 0"/>
    </bioloid_f3_fixed>

    <!-- Wrist servo -->
    <dynamixel_ax12_fixed
        parent="crane_plus_internal_lower_arm_joiner_link"
        name="crane_plus_internal_wrist_servo"
        color="black">
      <origin xyz="0 0 ${F3_SCREW_HEIGHT+AX12_ORIGIN_TO_END_SCREW}" rpy="0 ${M_PI/2} ${M_PI/2}"/>
    </dynamixel_ax12_fixed>

    <!-- Wrist bracket -->
    <bioloid_f2_revolute
        parent="crane_plus_internal_wrist_servo_link"
        name="crane_plus_wrist"
        color="grey"
        vlimit="${joints_vlimit}"
        llimit="-1.7"
        ulimit="1.7">
        <origin xyz="-${AX12_ORIGIN_TO_AXLE} 0 0" rpy="-${M_PI/2} 0 -${M_PI/2}"/>
    </bioloid_f2_revolute>

    <!-- Wrist joiner -->
    <bioloid_f3_fixed
        parent="crane_plus_wrist_link"
        name="crane_plus_internal_wrist_joiner"
        color="grey">
        <origin xyz="0 0 -${F2_AXLE_HEIGHT}" rpy="0 ${M_PI} ${M_PI/2}"/>
    </bioloid_f3_fixed>

    <!-- Gripper servo -->
    <dynamixel_ax12_fixed
        parent="crane_plus_internal_wrist_joiner_link"
        name="crane_plus_internal_gripper_servo"
        color="black">
        <origin xyz="${AX12_SIDE_SCREW_OFFSET} 0 ${F3_SCREW_HEIGHT+AX12_ORIGIN_TO_SIDE_SCREW}" rpy="${M_PI/2} ${M_PI} 0"/>
    </dynamixel_ax12_fixed>

    <!-- Fixed finger joiner -->
    <bioloid_f3_fixed
        parent="crane_plus_internal_gripper_servo_link"
        name="crane_plus_internal_fixed_finger_joiner"
        color="grey">
        <origin xyz="${AX12_ORIGIN_TO_END_SCREW+F3_SCREW_HEIGHT} 0 0" rpy="-${M_PI/2} 0 ${M_PI/2}"/>
    </bioloid_f3_fixed>

    <!-- Fixed finger -->
    <fixed_finger
        parent="crane_plus_internal_fixed_finger_joiner_link"
        name="crane_plus_internal_fixed_finger"
        color="black">
      <origin xyz="0 0 0" rpy="0 0 ${M_PI}"/>
    </fixed_finger>

    <!-- Tip of the fixed finger (useful in all sorts of ways) -->
    <joint name="crane_plus_fixed_finger_tip" type="fixed">
      <origin xyz="0.0745 0 -0.0106" rpy="${M_PI/2} 0 ${M_PI/2}"/>
      <parent link="crane_plus_internal_fixed_finger_link"/>
      <child link="crane_plus_fixed_finger_tip_link"/>
    </joint>
    <link name="crane_plus_fixed_finger_tip_link"/>

    <!-- Moving finger bracket (actual gripper joint) -->
    <bioloid_f2_revolute
        parent="crane_plus_internal_gripper_servo_link"
        name="crane_plus_moving_finger"
        color="grey"
        vlimit="${joints_vlimit}"
        llimit="-0.6"
        ulimit="0.65">
        <origin xyz="-${AX12_ORIGIN_TO_AXLE} 0 0" rpy="-${M_PI/2} 0 -${M_PI/2}"/>
    </bioloid_f2_revolute>

    <!-- Moving finger -->
    <moving_finger
        parent="crane_plus_moving_finger_link"
        name="crane_plus_internal_moving_finger_plate"
        color="black">
      <origin xyz="0 0 -${F2_AXLE_HEIGHT}" rpy="${M_PI} 0 0"/>
    </moving_finger>

    <!-- Tip of the moving finger (useful in all sorts of ways) -->
    <joint name="crane_plus_moving_finger_tip" type="fixed">
      <origin xyz="0.0923 0 -0.0194" rpy="${M_PI/2} 0 ${M_PI/2}"/>
      <parent link="crane_plus_internal_moving_finger_plate_link"/>
      <child link="crane_plus_moving_finger_tip_link"/>
    </joint>
    <link name="crane_plus_moving_finger_tip_link"/>

    <!-- A virtual link for the gripper to hang off, increasing the degrees of
         freedom by one and making it easier for MoveIt! to plan. -->
    <link name="crane_plus_gripper_link"/>
    <joint name="crane_plus_gripper_joint" type="revolute">
      <origin xyz="0 0 0.07" rpy="0 0 -${M_PI/2}"/>
      <axis xyz="1 0 0"/>
      <parent link="crane_plus_internal_wrist_joiner_link"/>
      <child link="crane_plus_gripper_link" />
      <limit effort="30" velocity="1" lower="-${M_PI}" upper="${M_PI}"/>
    </joint>

  </xacro:macro>
</robot>
